# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build

      - name: Deploy
        uses: appleboy/ssh-action@master
        if: github.event_name != 'pull_request'
        with:
          host: stldevs.com
          username: deploy
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            cd /opt/stldevs-svelte
            git pull
            npm ci
            npm run build
            sudo service stldevs-svelte restart
